---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        # This is jenkinsci/kubernetes-plugin, but image published under csanchez/jenkins-kubernetes. In future, check
        # if it gets migrated. Also, tags are not updated (only "latest"):
        # https://hub.docker.com/r/csanchez/jenkins-kubernetes/tags/
        image: csanchez/jenkins-kubernetes:latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 500Mi
        ports:
        - name: jenkins-http
          containerPort: 8080
        - name: jenkins-jnlp
          containerPort: 50000
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        env:
        - name: CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: "1Mi"
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: "1Mi"
        - name: JAVA_OPTS
          value: "-Xmx$(MEM_REQUEST)m"      
      volumes:
      - name: jenkins-data
        gcePersistentDisk:
          pdName: kubernetes-jenkins
          fsType: ext4
